services:
  - type: web
    name: whatsapp-bridge
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 8827088070:AAFZPz6PWpC5UGnhpbkCI1arq_9uuIePVV8
    healthCheckPath: /
